# Generated by Django 5.2 on 2025-04-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished',
            new_name='published',
        ),
    ]
