# Generated by Django 5.2.1 on 2025-05-15 06:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_about_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
