# Generated by Django 5.2.1 on 2025-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_aboutmodel_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='/blog_img/default_blog.jpg', null=True, upload_to=''),
        ),
    ]
