# Generated by Django 5.2.1 on 2025-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='blog_img/default.jpg', null=True, upload_to=''),
        ),
    ]
