# Generated by Django 5.2.1 on 2025-05-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='blog_img/default_blog.jpg', null=True, upload_to='blog_img/'),
        ),
    ]
